.enum $0000
; Reich Fox
EVENT_GET_SIDNEYS_PACK: ; $00
	.dsb 1
EVENT_VET_FIRST_TRIP: ; $01
	.dsb 1
EVENT_FIRST_BATH: ; $02
.ende

.enum $0000
; The June Cuddles
EVENT_FIRST_WALK: ; $00
	.dsb 1
EVENT_MEET_JUNE: ; $01
	.dsb 1
EVENT_FIRST_VISIT_WITH_JUNE: ; $02
	.dsb 1
EVENT_ADOPT_JUNE: ; $03
	.dsb 1
EVENT_FIRST_PLAYDATE_WITH_JUNE: ; $04
.ende

.enum $0000
; Ever n'Otis
EVENT_FIRST_BREAKFAST_DISTURBED: ; $00
	.dsb 1
EVENT_MEET_OTIS: ; $01
	.dsb 1
EVENT_WAIT_FOR_OTIS: ; $02
	.dsb 1
EVENT_READ_EXPRESSION_WRONG: ; $03
	.dsb 1
EVENT_ALL_THREE_MEET: ; $04
.ende

.enum $0000
LOC_FRIDIA: ; $00
	.dsb 1
LOC_VIRGINIA: ; $01
	.dsb 1
LOC_HOME: ; $02
	.dsb 1
LOC_JUNES: ; $03
	.dsb 1
LOC_OTIS: ; $04
	.dsb 1
LOC_PET_STORE: ; $05
	.dsb 1
LOC_PIZZA_PLACE: ; $06
	.dsb 1
LOC_VET: ; $07
	.dsb 1
LOC_BLOCK: ; $08
	.dsb 1
LOC_PARK: ; $09
	.dsb 1
LOC_PHILS: ; 0a
	.dsb 1
LOC_COURT: ; $0b
.ende

.enum $0000
EPISODE_REICH_FOX: ; $00
	.dsb 1
EPISODE_THE_JUNE_CUDDLES: ; $01
	.dsb 1
EPISODE_EVER_N_OTIS: ; $02
	.dsb 1
EPISODE_SIDNEY_STONE: ; $03
	.dsb 1
EPISODE_JUMP_THE_BUFF: ; $04
	.dsb 1
EPISODE_THANKS_TO_THE_CHIMNEY: ; $05
	.dsb 1
EPISODE_MOLEPOOL: ; $06
	.dsb 1
EPISODE_NAME_BREAK: ; $07
	.dsb 1
EPISODE_WHAT_SHOULD_WE_DO_WITH_SIDNEY: ; $08
	.dsb 1
EPISODE_GOOD_ANSWER: ; $09
	.dsb 1
EPISODE_UNDER_THE_CARROTS: ; $0a
	.dsb 1
EPISODE_TAURINE_FOR_DINNER: ; $0b
	.dsb 1
EPISODE_THE_INCREDIBLE_MOVING_DOG: ; $0c
	.dsb 1
EPISODE_CARD_OF_TREATS: ; $0d
	.dsb 1
EPISODE_BITE_BOARD: ; $0e
	.dsb 1
EPISODE_LAWN_SIGN: ; $0f
	.dsb 1
EPISODE_LAUNDRY: ; $10
	.dsb 1
EPISODE_AT_ASSISTANCE: ; $11
	.dsb 1
EPISODE_GOING_FOR_THE_BOOK: ; $12
	.dsb 1
EPISODE_EVERY_SONG_IS_PERSONALIZED: ; $13
	.dsb 1
EPISODE_PIONEERS_HUT: ; $14
	.dsb 1
EPISODE_BUILT_UP_A_LIFE: ; $15
	.dsb 1
EPISODE_CARRYOVER_DREAMS: ; $16
	.dsb 1
EPISODE_VIXEN_VISITOR: ; $17
	.dsb 1
EPISODE_OTIS_ODOR: ; $18
	.dsb 1
EPISODE_HORNET_TAG: ; $19
	.dsb 1
EPISODE_FIRST_REUNION: ; $1a
	.dsb 1
EPISODE_COUNT:

NUM_EPISODES = EPISODE_COUNT >> 1

.ende