TITLESCREENOPTION_MAIN_MENU = 0
TITLESCREENOPTION_DELETE_SAVE_FILE = 1
TITLESCREENOPTION_RESTART = 2

NUM_TITLESCREENOPTION = 3

A_BUTTON = 7
B_BUTTON = 6
SELECT_BUTTON = 5
START_BUTTON = 4
UP_BUTTON = 3
DOWN_BUTTON = 2
LEFT_BUTTON = 1
RIGHT_BUTTON = 0