.enum $0000
TITLESCREENOPTION_MAIN_MENU:
	.dsb 1
TITLESCREENOPTION_DELETE_SAVE_FILE:
	.dsb 1
TITLESCREENOPTION_RESTART:
	.dsb 1

NUM_TITLESCREENOPTION:

A_BUTTON = 7
B_BUTTON = 6
SELECT_BUTTON = 5
START_BUTTON = 4
UP_BUTTON = 3
DOWN_BUTTON = 2
LEFT_BUTTON = 1
RIGHT_BUTTON = 0
.ende

TITLE_SCREEN_DURATION = $d7f