ITEM_NAMES = 1
CHR_FULL_NAMES = 2
CHR_NAMES = 3
LOC_NAMES = 4
EPISODE_NAMES = 5

; name lengths
ITEM_NAME_LENGTH = 13
CHR_FULL_NAME_LENGTH = 15
CHR_NAME_LENGTH = 6
LOC_NAME_LENGTH = 15

ITEM_NONE        = $00
ITEM_DEBIT_CARD  = $01
ITEM_TREAT       = $02
ITEM_BANK_LETTER = $03
ITEM_PACK        = $04

CHARACTER_NONE = $00
CHARACTER_IGGY = $01
CHARACTER_JUNE = $02
CHARACTER_OTIS = $03
CHARACTER_PHIL = $04
CHARACTER_DILL = $05
CHARACTER_LILA = $06
CHARACTER_GARY = $07
CHARACTER_SID  = $08
CHARACTER_09   = $09
CHARACTER_0A   = $0a
CHARACTER_0B   = $0b
CHARACTER_ALEX = $0c
CHARACTER_0D   = $0d
CHARACTER_0E   = $0e
CHARACTER_0F   = $0f
