ITEM_NAMES = 1
CHR_FULL_NAMES = 2
CHR_NAMES = 3
LOC_NAMES = 4
EPISODE_NAMES = 5

; name lengths
ITEM_NAME_LENGTH = 13
CHR_FULL_NAME_LENGTH = 15
CHR_NAME_LENGTH = 6
LOC_NAME_LENGTH = 15

ITEM_NONE        = $00
ITEM_DEBIT_CARD  = $01
ITEM_TREAT       = $02
ITEM_BANK_LETTER = $03
ITEM_PACK        = $04
