.enum $0001
P_Hat:
SFX_EXCLAMATION_1:	.dsb 1
P_Crash:
SFX_EXCLAMATION_2:	.dsb 1
P_QHat:
SFX_EXCLAMATION_3:	.dsb 1
P_OHat:
SFX_CURSOR_1:		.dsb 1
P_DHat:
SFX_CURSOR_2:		.dsb 1
P_DClap:
SFX_CURSOR_3:		.dsb 1
P_Snare:
SFX_SELECT_1:		.dsb 1
P_Kick:
SFX_SELECT_2:		.dsb 1
SFX_SELECT_3:		.dsb 1
SFX_IGGY_IDLE:		.dsb 1
SFX_JUNE_IDLE:		.dsb 1
SFX_OTIS_IDLE:		.dsb 1
SFX_IGGY_ANGRY:		.dsb 1
SFX_JUNE_ANGRY:		.dsb 1
SFX_OTIS_ANGRY:		.dsb 1
SFX_IGGY_CURIOUS:	.dsb 1
SFX_JUNE_CURIOUS:	.dsb 1
SFX_OTIS_CURIOUS:	.dsb 1
SFX_IGGY_TALKING:	.dsb 1
SFX_JUNE_TALKING:	.dsb 1
SFX_OTIS_TALKING:	.dsb 1
SFX_IGGY_BUMMED:	.dsb 1
SFX_JUNE_BUMMED:	.dsb 1
SFX_OTIS_BUMMED:	.dsb 1
NOISE_SFX:
P_Click:
SFX_DOOR_CLICK:		.dsb 1
P_Claves:
SFX_DOOR_SHUT:		.dsb 1
P_Conga:
SFX_DOOR_SLAM:		.dsb 1
SFX_SINK:		.dsb 1
SFX_STOP:		.dsb 1
SFX_JUMP:		.dsb 1
SFX_FLAP:
NUM_SFX:
	.dsb 1
SFX_OBJECTIVE_COMPLETE: ; $1e
.ende