CharacterFullNames:
	.db "Iggy Reich@"
	.db "Junior Fey@"
	.db "James Raren@"
	.db "James Raren@"
	.db "Phillip Reich@"
	.db "Dilan Fey@"
	.db "Lila Fey@"
	.db "Gary Raren@"
	.db "Sydney Esced@"
	.db "INCIDENTAL-LINE@"
	.db "RECEPTIONIST-1@"
	.db "VETERENARIAN-1@"

CharacterNames:
	.db "Iggy@"
	.db "June@"
	.db "Jim@"
	.db "Otis@"
	.db "Phil@"
	.db "Dill@"
	.db "Lila@"
	.db "Gary@"
	.db "Sydney@"
	.db "INC.C1@"
	.db "REC.01@"
	.db "VET.01@"
