NoiseSFXPointersLo:
	.dl NoiseSFX_Hihat
	.dl NoiseSFX_Crash
	.dl NoiseSFX_QuietHihat
	.dl NoiseSFX_HihatOpen
	.dl NoiseSFX_DryHihat
	.dl NoiseSFX_DoubleClap
	.dl NoiseSFX_Snare
	.dl NoiseSFX_Kick
	.dl NoiseSFX_None
	.dl NoiseSFX_None
	.dl NoiseSFX_None
	.dl NoiseSFX_None
	.dl NoiseSFX_None
	.dl NoiseSFX_None
	.dl NoiseSFX_None
	.dl NoiseSFX_None
	.dl NoiseSFX_None
	.dl NoiseSFX_None
	.dl NoiseSFX_None
	.dl NoiseSFX_None
	.dl NoiseSFX_None
	.dl NoiseSFX_None
	.dl NoiseSFX_None
	.dl NoiseSFX_None
	.dl NoiseSFX_DoorClick
	.dl NoiseSFX_DoorClose
	.dl NoiseSFX_DoorSlam
	.dl NoiseSFX_Sink
	.dl NoiseSFX_None
	.dl NoiseSFX_None
	.dl NoiseSFX_Flap
	.dl NoiseSFX_None
	.dl NoiseSFX_None

NoiseSFXPointersHi:
	.dh NoiseSFX_Hihat
	.dh NoiseSFX_Crash
	.dh NoiseSFX_QuietHihat
	.dh NoiseSFX_HihatOpen
	.dh NoiseSFX_DryHihat
	.dh NoiseSFX_DoubleClap
	.dh NoiseSFX_Snare
	.dh NoiseSFX_Kick
	.dh NoiseSFX_None
	.dh NoiseSFX_None
	.dh NoiseSFX_None
	.dh NoiseSFX_None
	.dh NoiseSFX_None
	.dh NoiseSFX_None
	.dh NoiseSFX_None
	.dh NoiseSFX_None
	.dh NoiseSFX_None
	.dh NoiseSFX_None
	.dh NoiseSFX_None
	.dh NoiseSFX_None
	.dh NoiseSFX_None
	.dh NoiseSFX_None
	.dh NoiseSFX_None
	.dh NoiseSFX_None
	.dh NoiseSFX_DoorClick
	.dh NoiseSFX_DoorClose
	.dh NoiseSFX_DoorSlam
	.dh NoiseSFX_Sink
	.dh NoiseSFX_None
	.dh NoiseSFX_None
	.dh NoiseSFX_Flap
	.dh NoiseSFX_None
	.dh NoiseSFX_None
