Pulse2SFXPointersLO:
	.dl Pulse2SFX_None
	.dl Pulse2SFX_None
	.dl Pulse2SFX_None
	.dl Pulse2SFX_None
	.dl Pulse2SFX_None
	.dl Pulse2SFX_None
	.dl Pulse2SFX_None
	.dl Pulse2SFX_None
	.dl Pulse2SFX_None
	.dl Pulse2SFX_None
	.dl Pulse2SFX_None
	.dl Pulse2SFX_None
	.dl Pulse2SFX_None
	.dl Pulse2SFX_None
	.dl Pulse2SFX_None
	.dl Pulse2SFX_None
	.dl Pulse2SFX_None
	.dl Pulse2SFX_None
	.dl Pulse2SFX_None
	.dl Pulse2SFX_None
	.dl Pulse2SFX_None
	.dl Pulse2SFX_None
	.dl Pulse2SFX_None
	.dl Pulse2SFX_None
	.dl Pulse2SFX_None
	.dl Pulse2SFX_None
	.dl Pulse2SFX_None
	.dl Pulse2SFX_None
	.dl Pulse2SFX_Stop

Pulse2SFXPointersHI:
	.dh Pulse2SFX_None
	.dh Pulse2SFX_None
	.dh Pulse2SFX_None
	.dh Pulse2SFX_None
	.dh Pulse2SFX_None
	.dh Pulse2SFX_None
	.dh Pulse2SFX_None
	.dh Pulse2SFX_None
	.dh Pulse2SFX_None
	.dh Pulse2SFX_None
	.dh Pulse2SFX_None
	.dh Pulse2SFX_None
	.dh Pulse2SFX_None
	.dh Pulse2SFX_None
	.dh Pulse2SFX_None
	.dh Pulse2SFX_None
	.dh Pulse2SFX_None
	.dh Pulse2SFX_None
	.dh Pulse2SFX_None
	.dh Pulse2SFX_None
	.dh Pulse2SFX_None
	.dh Pulse2SFX_None
	.dh Pulse2SFX_None
	.dh Pulse2SFX_None
	.dh Pulse2SFX_None
	.dh Pulse2SFX_None
	.dh Pulse2SFX_None
	.dh Pulse2SFX_None
	.dh Pulse2SFX_Stop