SoundEffectDestinations:
	.db zDPCMSFX
	.db zDPCMSFX
	.db zDPCMSFX
	.db zDPCMSFX
	.db zDPCMSFX
	.db zDPCMSFX
	.db zDPCMSFX
	.db zDPCMSFX
	.db zDPCMSFX
	.db zDPCMSFX
	.db zDPCMSFX
	.db zDPCMSFX
	.db zDPCMSFX
	.db zDPCMSFX
	.db zDPCMSFX
	.db zDPCMSFX
	.db zDPCMSFX
	.db zDPCMSFX
	.db zDPCMSFX
	.db zDPCMSFX
	.db zDPCMSFX
	.db zDPCMSFX
	.db zDPCMSFX
	.db zDPCMSFX
	.db zNoiseDrumSFX
	.db zNoiseDrumSFX
	.db zNoiseDrumSFX
	.db zNoiseDrumSFX
	.db zNoiseDrumSFX
	.db zNoiseDrumSFX + 1