SoundEffectDestinations:
	.db zDPCMSFX
	.db zDPCMSFX
	.db zDPCMSFX
	.db zDPCMSFX
	.db zDPCMSFX
	.db zDPCMSFX
	.db zDPCMSFX
	.db zDPCMSFX
	.db zDPCMSFX
	.db zDPCMSFX
	.db zDPCMSFX
	.db zDPCMSFX
	.db zDPCMSFX
	.db zDPCMSFX
	.db zDPCMSFX
	.db zDPCMSFX
	.db zDPCMSFX
	.db zDPCMSFX
	.db zDPCMSFX
	.db zDPCMSFX
	.db zDPCMSFX
	.db zDPCMSFX
	.db zDPCMSFX
	.db zDPCMSFX
	.db zNoiseDrumSFX
	.db zNoiseDrumSFX
	.db zNoiseDrumSFX
	.db zNoiseDrumSFX
	.db zPulse2SFX
	.db zPulse2SFX
	.db zNoiseDrumSFX
	.db zNoiseDrumSFX + 1