SFX:
	dba PRG_Audio,  SFX_FoxExclamation
	dba PRG_Audio,  SFX_CatExclamation
	dba PRG_Audio,  SFX_DogExclamation
	dba PRG_Audio,  SFX_FoxCursor
	dba PRG_Audio,  SFX_CatCursor
	dba PRG_Audio,  SFX_DogCursor
	dba PRG_Audio,  SFX_FoxSelect
	dba PRG_Audio,  SFX_CatSelect
	dba PRG_Audio,  SFX_DogSelect
	dba PRG_Audio,  SFX_IggyVoice0
	dba PRG_Audio,  SFX_JuneVoice0
	dba PRG_Audio,  SFX_OtisVoice0
	dba PRG_Audio,  SFX_IggyVoice1
	dba PRG_Audio,  SFX_JuneVoice1
	dba PRG_Audio,  SFX_OtisVoice1
	dba PRG_Audio,  SFX_IggyVoice2
	dba PRG_Audio,  SFX_JuneVoice2
	dba PRG_Audio,  SFX_OtisVoice2
	dba PRG_Audio,  SFX_IggyVoice3
	dba PRG_Audio,  SFX_JuneVoice3
	dba PRG_Audio,  SFX_OtisVoice3
	dba PRG_Audio,  SFX_IggyVoice4
	dba PRG_Audio,  SFX_JuneVoice4
	dba PRG_Audio,  SFX_OtisVoice4
