.include "src/sound/music-part-pointers-1.asm"
.include "src/sound/music-headers-1.asm"
.include "src/sound/music-pointers-1.asm"
.include "src/sound/instruments-1.asm"

.include "src/sound/music/title-1-5.asm"
.include "src/sound/music/title-6.asm"
.include "src/sound/music/title-7.asm"
.include "src/sound/music/title-8.asm"
.include "src/sound/music/title-9.asm"
.include "src/sound/music/title-10.asm"