.include "src/engine/overworld.asm"
.include "src/data/overworld/iggys-room.asm"
.include "src/data/overworld/collision/iggys-room.asm"
.include "src/data/overworld/sprites/normal-offsets.asm"
.include "src/data/overworld/sprites/z-chr.asm"
